package com.ahuralearn.file.service.impl;

import cn.hutool.core.util.StrUtil;
import com.ahuralearn.common.enums.ResultCode;
import com.ahuralearn.common.exceptions.BusinessException;
import com.ahuralearn.common.utils.UserContext;
import com.ahuralearn.file.domain.po.File;
import com.ahuralearn.file.domain.vo.RegenerateVO;
import com.ahuralearn.file.domain.vo.SummaryVO;
import com.ahuralearn.file.service.IFileService;
import com.ahuralearn.file.service.ISummaryService;
import com.ahuralearn.file.utils.FileAnalyzer;
import dev.langchain4j.model.chat.ChatModel;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * <p>
 * AI summarization service impl
 * </p>
 * Powers the AI-Summarization view. The summary is generated by Qwen (Alibaba
 * DashScope) via LangChain4j from the file's extracted text, and the key points
 * are derived from that summary. Nothing is stored — both are produced fresh on
 * each request, so they always reflect the latest text. It owns no table of its
 * own and reads the File entity through {@link IFileService}.
 *
 * @author Dariush
 * @since 2026-06-18
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SummaryServiceImpl implements ISummaryService {

    // Upper bound on the document text sent to the model in one request.
    private static final int MAX_INPUT_CHARS = 20000;

    // Each "Regenerate" picks a different framing at random, so the new summary is
    // genuinely different (different emphasis) rather than the same text reworded.
    private static final String[] SUMMARY_ANGLES = {
            "Write a clear, concise executive summary (a short paragraph) capturing the main ideas.",
            "Summarize the document from a fresh angle: emphasize the key concepts and how they relate to each other.",
            "Write a summary that focuses on the practical applications, procedures and concrete examples in the document.",
            "Summarize by highlighting the most important takeaways a student should remember for an exam, phrased differently from a standard overview.",
            "Give a big-picture summary first, then the one or two details that matter most."
    };

    private final IFileService fileService;

    // Qwen/DashScope chat model (auto-configured by the langchain4j starter).
    // Resolved lazily so the app still boots if the API key is missing/invalid;
    // that only surfaces as a clean business error on first use.
    private final ObjectProvider<ChatModel> chatModelProvider;

    /**
     * Build a file's summary + key points from its extracted text (read-only, for the UI).
     * The summary comes from the LLM; the key points are split out of that summary.
     */
    @Override
    public SummaryVO getSummary(Long documentId) {
        File file = requireFile(documentId);
        String text = file.getExtractedText() == null ? "" : file.getExtractedText();
        String summary = summarize(text);
        List<String> keyPoints = FileAnalyzer.keyPoints(summary, 4);
        return new SummaryVO(file.getId(), file.getOriginalName(), summary, keyPoints, file.getStatus());
    }

    /**
     * Summaries are generated on read, so there is nothing stored to rebuild — the next
     * getSummary() already asks the model again against the latest extracted text. Kept
     * so the UI's "regenerate" action still gets a clean acknowledgement.
     */
    @Override
    public RegenerateVO regenerate(Long documentId) {
        File file = requireFile(documentId);
        return new RegenerateVO(file.getId(), "Summary regenerated successfully");
    }

    /**
     * Summarize the extracted text with Qwen (DashScope). Blank text short-circuits
     * (no model call); a missing/invalid key surfaces as a clean business error.
     */
    private String summarize(String text) {
        if (StrUtil.isBlank(text))
            return "No text could be extracted from this document, so there is nothing to summarize.";

        String clipped = text.length() <= MAX_INPUT_CHARS ? text : text.substring(0, MAX_INPUT_CHARS);
        String angle = SUMMARY_ANGLES[ThreadLocalRandom.current().nextInt(SUMMARY_ANGLES.length)];
        String prompt = """
                You are an academic study assistant. %s
                Keep it concise but complete: about 150-200 words in two short paragraphs. Cover the
                main ideas clearly, but leave out minor details.
                Stay grounded in the text — do not invent facts it does not contain.
                Write in plain, natural prose. Do NOT use Markdown or any special formatting
                (no #, *, -, **, backticks or tables) and no LaTeX; write any symbols, units and
                math in plain words (for example "ohms", "V_EE", "255 x 255").

                Document:
                %s""".formatted(angle, clipped);
        try {
            return chatModelProvider.getObject().chat(prompt);
        } catch (Exception e) {
            log.error("Qwen (DashScope) summary request failed", e);
            throw new BusinessException("The AI summarizer is unavailable right now. "
                    + "Check the DashScope API key (langchain4j.community.dashscope.chat-model.api-key) and try again.");
        }
    }

    /**
     * Load the caller's file by id, or fail with 404. Scoped to the owner (from the
     * JWT) so another user's document simply looks "not found".
     */
    private File requireFile(Long documentId) {
        File file = fileService.lambdaQuery()
                .eq(File::getId, documentId)
                .eq(File::getUserId, UserContext.getUser())
                .one();
        if (file == null)
            throw new BusinessException(ResultCode.NOT_FOUND);
        return file;
    }
}
